version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - build

jobs:
  build:
    working_directory: ~/projectApp
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: pip install -r requirements.txt
      - run:
          name: run-tests
          command: python manage.py test
    deploy:
      docker:
        - image: cimg/python:3.8
      steps:
        - run:
            name: deploy-application
            command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "rm -rf projectApp/;git clone https://github.com/DevOpsSec-Organization/projectApp.git; source projectApp/deploy.sh"
    
