version: 2.1

jobs:
  build:
    working_directory: ~/projectApp
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: install-dependencies
          command: pip install -r requirements.txt
      - run:
          name: run-tests
          command: python manage.py test

  deploy:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: deploy-application
          command: ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS "rm -rf projectApp/; git clone git@github.com:DevOpsSec-Organization/projectApp.git; source projectApp/deploy.sh"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main
